export default [
  {
    name: 'Audio',
    iconPath: './Icons/audio-file.png',
    extList: [
      '.wpl',
      '.wma',
      '.wav',
      '.mpa',
      '.mp3',
      '.midi',
      '.mid',
      '.cda',
      '.aif',
      '.mov',
    ],
  },
  { name: 'Text', iconPath: './Icons/text.png', extList: ['.txt'] },
  {
    name: 'Compressed',
    iconPath: './Icons/zip.png',
    extList: [
      '.7z',
      '.arj',
      '.deb',
      '.pkg',
      '.rar',
      '.rpm',
      '.tar.gz',
      '.z',
      '.zip',
    ],
  },
  {
    name: 'DiskImage',
    iconPath: './Icons/dvd.png',
    extList: ['.vcd', '.toast', '.iso', '.dmg', '.bin'],
  },
  {
    name: 'Database',
    iconPath: './Icons/database.png',
    extList: [
      '.csv',
      '.dat',
      '.db',
      '.dbf',
      '.log',
      '.mdb',
      '.sav',
      '.sql',
      '.tar',
      '.xml',
    ],
  },
  {
    name: 'Email',
    iconPath: './Icons/email.png',
    extList: ['email', '.eml', '.emlx', '.msg', '.oft', '.ost', '.pst', '.vcf'],
  },
  {
    name: 'SysFiles',
    iconPath: './Icons/administration.png',
    extList: [
      '.apk',
      '.bat',
      '.bin',
      '.cgi',
      '.pl',
      '.com',
      '.gadget',
      '.exe',
      '.jar',
      '.msi',
      '.wsf',
    ],
  },
  {
    name: 'Font',
    iconPath: './Icons/font.png',
    extList: ['.fon', '.otf', '.ttf', '.fnt'],
  },
  {
    name: 'Image',
    iconPath: './Icons/image.png',
    extList: [
      '.ai',
      '.bmp',
      '.gif',
      '.ico',
      '.jpeg',
      '.jpg',
      '.png',
      '.ps',
      '.psd',
      '.svg',
      '.tif',
      '.tiff',
    ],
  },
  {
    name: 'InternetThings',
    iconPath: './Icons/browser.png',
    extList: [
      '.asp',
      '.aspx',
      '.cer',
      '.cfm',
      '.cgi',
      '.pl',
      '.part',
      '.php',
      '.xhtml',
      '.rss',
    ],
  },
  {
    name: 'CLang',
    iconPath: './Icons/icons8-c-programming-512.png',
    extList: ['.c'],
  },
  { name: 'CppLang', iconPath: './Icons/cpp.png', extList: ['.cpp', '.h'] },
  { name: 'JavaLang', iconPath: './Icons/java.png', extList: ['.java'] },
  { name: 'JavaClass', iconPath: './Icons/java.png', extList: ['.class'] },
  { name: 'PythonLang', iconPath: './Icons/python.png', extList: ['.py'] },
  { name: 'Css', iconPath: './Icons/css-3.png', extList: ['.css', '.scss'] },
  { name: 'Html', iconPath: './Icons/html.png', extList: ['.htm', '.html'] },
  { name: 'Js', iconPath: './Icons/js-format.png', extList: ['.js', '.jsx'] },
  { name: 'Ts', iconPath: './Icons/js-format.png', extList: ['.ts', '.tsx'] },
  {
    name: 'Ppts',
    iconPath: './Icons/ppt.png',
    extList: ['.pptx', '.ppt', '.pps', '.odp', '.key'],
  },
  {
    name: 'SpreedSheets',
    iconPath: './Icons/xls.png',
    extList: ['.xlsx', '.xlsm', '.xls', '.ods', '.tsv', '.numbers'],
  },
  {
    name: 'SysFiles',
    iconPath: './Icons/system.png',
    extList: [
      '.tmp',
      '.sys',
      '.msi',
      '.lnk',
      '.ini',
      '.icns',
      '.drv',
      '.dmp',
      '.dll',
      '.cur',
      '.cpl',
      '.cfg',
      '.cab',
      '.bak',
    ],
  },
  {
    name: 'Video',
    iconPath: './Icons/video-file.png',
    extList: [
      '.3g2',
      '.3gp',
      '.avi',
      '.flv',
      '.h264',
      '.m4v',
      '.mkv',
      '.mov',
      '.mp4',
      '.mpg',
      '.mpeg',
      '.rm',
      '.swf',
      '.vob',
      '.wmv',
    ],
  },
  {
    name: 'Docs',
    iconPath: './Icons/google-docs.png',
    extList: [
      '.wpd',
      '.tex',
      '.rtf',
      '.odt',
      '.docx',
      '.doc',
      '.pages',
      '.pdf',
    ],
  },
];
